/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasilitekasir;

import dao.MenuDAO;
import model.Menu;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import model.KategoriItem;
import javax.swing.JComboBox;
/**
 *
 * @author ALFIAN WIDHI
 */
public class InventoryFrame extends javax.swing.JFrame {
    private DefaultTableModel modelMenu;
    private int selectedMenuId = -1;

    /**
     * Creates new form NewInventoryFrame
     */
    public InventoryFrame() {
        initComponents();
        
        modelMenu = new DefaultTableModel(new String[]{"ID", "Nama", "Harga", "Stok", "Kategori"}, 0);
        jTable1.setModel(modelMenu);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);   
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);  
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);   
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);  
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(120); 
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);

        loadKategoriToComboBox();

        loadMenuToTable();

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            int row = jTable1.getSelectedRow();
            if (row != -1) {
                selectedMenuId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                jTextFieldNama.setText(jTable1.getValueAt(row, 1).toString());
                jTextFieldHarga.setText(jTable1.getValueAt(row, 2).toString());
                jTextFieldStok.setText(jTable1.getValueAt(row, 3).toString());
                
                String kategoriNama = jTable1.getValueAt(row, 4).toString();
                for (int i = 0; i < jComboBoxKategori.getItemCount(); i++) {
                    if (jComboBoxKategori.getItemAt(i).toString().equals(kategoriNama)) {
                        jComboBoxKategori.setSelectedIndex(i);
                        break;
                    }
                }
            }
        });
    }

    private void loadKategoriToComboBox() {
        jComboBoxKategori.removeAllItems();
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/litekasir", "root", "")) {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT id, nama FROM kategori");
            while (rs.next()) {
                jComboBoxKategori.addItem(new KategoriItem(rs.getInt("id"), rs.getString("nama")));
            }
            rs.close();
            st.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal load kategori: " + e.getMessage());
        }
    }

    private void loadMenuToTable() {
        modelMenu.setRowCount(0);
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/litekasir", "root", "")) {
            String sql = "SELECT m.id, m.nama, m.harga, m.stok, k.nama AS kategori FROM menu m JOIN kategori k ON m.id_kategori = k.id";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                modelMenu.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nama"),
                    rs.getInt("harga"),
                    rs.getInt("stok"),
                    rs.getString("kategori")
                });
            }
            rs.close();
            st.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal load menu: " + e.getMessage());
        }
    }

    private void clearInput() {
        jTextFieldNama.setText("");
        jTextFieldHarga.setText("");
        jTextFieldStok.setText("");
        jComboBoxKategori.setSelectedIndex(-1);
        selectedMenuId = -1;
        jTable1.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldHarga = new javax.swing.JTextField();
        jTextFieldStok = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxKategori = new javax.swing.JComboBox<>();
        btnTambahKategori = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Nama");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 181, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Harga");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 181, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Stok");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 181, -1));

        jTextFieldNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 181, 30));

        jTextFieldHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jTextFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 181, 30));

        jTextFieldStok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jTextFieldStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStokActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 181, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 51, 204));
        btnUpdate.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, 34));

        btnDelete.setBackground(new java.awt.Color(0, 51, 204));
        btnDelete.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 90, 33));

        btnTambah.setBackground(new java.awt.Color(0, 51, 204));
        btnTambah.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel3.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, 34));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jTable1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 480, 380));

        btnKembali.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 0, 153));
        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel3.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("INVENTORY");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Kategori");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 181, -1));

        jComboBoxKategori.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jComboBoxKategori.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKategoriActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 30));

        btnTambahKategori.setBackground(new java.awt.Color(0, 51, 204));
        btnTambahKategori.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTambahKategori.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahKategori.setText("+");
        btnTambahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKategoriActionPerformed(evt);
            }
        });
        jPanel3.add(btnTambahKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 40, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DAFTAR MENU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel7)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 480, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rm222-mind-31.jpg"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 700, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTextFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaActionPerformed

    private void jTextFieldStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStokActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih menu yang ingin diupdate!");
            return;
        }
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/litekasir", "root", "")) {
            int idMenu = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            String nama = jTextFieldNama.getText().trim();
            int harga = Integer.parseInt(jTextFieldHarga.getText().trim());
            int stok = Integer.parseInt(jTextFieldStok.getText().trim());
            KategoriItem kategori = (KategoriItem) jComboBoxKategori.getSelectedItem();
            if (kategori == null) {
                JOptionPane.showMessageDialog(this, "Kategori harus dipilih!");
                return;
            }
            int idKategori = kategori.getId();

            String sql = "UPDATE menu SET nama=?, harga=?, stok=?, id_kategori=? WHERE id=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            ps.setInt(2, harga);
            ps.setInt(3, stok);
            ps.setInt(4, idKategori);
            ps.setInt(5, idMenu);
            ps.executeUpdate();
            ps.close();
            JOptionPane.showMessageDialog(this, "Menu berhasil diupdate!");
            loadMenuToTable();
            clearInput();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Gagal update menu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedMenuId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih menu yang ingin dihapus!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus menu ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/litekasir", "root", "")) {
                String sql = "DELETE FROM menu WHERE id=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, selectedMenuId);
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(this, "Menu berhasil dihapus!");
                loadMenuToTable();
                clearInput();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus menu: " + e.getMessage());
            }
        }   
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nama = jTextFieldNama.getText().trim();
        String hargaStr = jTextFieldHarga.getText().trim();
        String stokStr = jTextFieldStok.getText().trim();
        KategoriItem kategori = (KategoriItem) jComboBoxKategori.getSelectedItem();

        if (nama.isEmpty() || hargaStr.isEmpty() || stokStr.isEmpty() || kategori == null) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/litekasir", "root", "")) {
            String sql = "INSERT INTO menu (nama, harga, stok, id_kategori) VALUES (?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            ps.setInt(2, Integer.parseInt(hargaStr));
            ps.setInt(3, Integer.parseInt(stokStr));
            ps.setInt(4, kategori.getId());
            ps.executeUpdate();
            ps.close();
            JOptionPane.showMessageDialog(this, "Menu berhasil ditambahkan!");
            loadMenuToTable();
            clearInput();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Gagal tambah menu: " + e.getMessage());
        }   
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new DashboardFrame().setVisible(true);
            dispose();  
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void jComboBoxKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKategoriActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_jComboBoxKategoriActionPerformed

    private void btnTambahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKategoriActionPerformed
        // TODO add your handling code here:                                                
        String namaKategori = JOptionPane.showInputDialog(this, "Masukkan Nama Kategori Baru:");
        if (namaKategori != null && !namaKategori.trim().isEmpty()) {
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/litekasir", "root", "")) {
                String sql = "INSERT INTO kategori (nama) VALUES (?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, namaKategori.trim());
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(this, "Kategori berhasil ditambahkan!");
                loadKategoriToComboBox(); 
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal tambah kategori: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnTambahKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahKategori;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<KategoriItem> jComboBoxKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldStok;
    // End of variables declaration//GEN-END:variables
}
