/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasilitekasir;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Session;
/**
 *
 * @author ALFIAN WIDHI
 */
    public class LoginFrame extends javax.swing.JFrame {
        private PreparedStatement stat;
        private ResultSet rs;
        DatabaseConnection dc = new DatabaseConnection();
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();      

        JLabel lblTentang = new JLabel("<html><u>Tentang Aplikasi</u></html>");
        lblTentang.setForeground(Color.BLUE);
        lblTentang.setCursor(new Cursor(Cursor.HAND_CURSOR));

        JLabel lblHubungi = new JLabel("<html><u>Hubungi Admin</u></html>");
        lblHubungi.setForeground(Color.BLUE);
        lblHubungi.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblTentang.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                AboutFrame tentangFrame = new AboutFrame();
                tentangFrame.setLocationRelativeTo(null);
                tentangFrame.setVisible(true);
                dispose();
            }
        });

        lblHubungi.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new java.net.URI("https://wa.me/6285732491409"));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Gagal membuka link: " + ex.getMessage());
                }
            }
        });   
        panelFooter.add(lblTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));
        panelFooter.add(lblHubungi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelFooter = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cbRole = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTentang = new javax.swing.JLabel();
        lblHubungi = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFooter.setBackground(new java.awt.Color(153, 153, 153));
        panelFooter.setForeground(new java.awt.Color(153, 153, 153));
        panelFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        panelFooter.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 148, 220, 30));

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panelFooter.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, 30));

        cbRole.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "KASIR", " " }));
        cbRole.setBorder(null);
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });
        panelFooter.add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 220, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        panelFooter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        panelFooter.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Role");
        panelFooter.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnSignup.setBackground(new java.awt.Color(0, 51, 204));
        btnSignup.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("SIGN UP");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        panelFooter.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 93, -1));

        btnLogin.setBackground(new java.awt.Color(0, 51, 204));
        btnLogin.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelFooter.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 93, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("LOGIN LITEKASIR");
        panelFooter.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel5.setText("Selamat Datang di LiteKasir Aplikasi Kasir Sederhana");
        panelFooter.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblTentang.setForeground(new java.awt.Color(0, 51, 204));
        lblTentang.setText("Tentang Aplikasi");
        panelFooter.add(lblTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        lblHubungi.setForeground(new java.awt.Color(0, 51, 204));
        lblHubungi.setText("Hubungi Admin");
        panelFooter.add(lblHubungi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("|");
        panelFooter.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 10, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rm222-mind-31.jpg"))); // NOI18N
        panelFooter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 410, 500));

        jPanel1.add(panelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 380, 500));

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO 2.png"))); // NOI18N
        jLabel8.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel8)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:       
            String username = txtUsername.getText();
            String password = new String(txtPassword.getPassword());
            String role = cbRole.getSelectedItem().toString().toLowerCase();

       try (Connection conn = dc.getConnection()) {
           String sql = "SELECT * FROM users WHERE username=? AND password=? AND LOWER(role)=?";
           stat = conn.prepareStatement(sql);
           stat.setString(1, username);
           stat.setString(2, password);
           stat.setString(3, role);

           rs = stat.executeQuery();
           if (rs.next()) {
               
               String namaKasir = rs.getString("username"); 
               TransaksiFrame transaksiFrame = new TransaksiFrame();

               String dbRole = rs.getString("role").toLowerCase();
               JOptionPane.showMessageDialog(this, "Login Berhasil sebagai " + dbRole + "!");

               Session.setUserName(namaKasir);
               Session.setRole(role);
               
               DashboardFrame dashboard = new DashboardFrame();
               dashboard.setRole(dbRole);
               dashboard.setVisible(true);
               this.dispose();
           } else {
               JOptionPane.showMessageDialog(this, "Login gagal! Username/password/role salah.");
           }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
       }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here: 
        new SignupFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblHubungi;
    private javax.swing.JLabel lblTentang;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
